server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: blog

  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    open-in-view: true

  sql:
    init:
      encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true